### ISSUE TITLE
数据超过500条后，点选会出现错行，点击某一单元格，往上数第三个单元格会被选中，而且选择的border有错行

### ISSUE THREAD

**Issue by zhangguowei0916** [KevinMint55/vue-willtable#1]
![image](https://user-images.githubusercontent.com/10540546/62773510-e6d40b00-bad4-11e9-9fba-594a27b6e1da.png)

**Comment by KevinMint55** [comment]
![image](https://user-images.githubusercontent.com/21260293/62847799-c8575500-bd0a-11e9-8c86-c5f5cce0f949.png)
我测试了1000条数据并未重现该问题，请问是否还有其他条件会产生这种情况。

**Comment by zhangguowei0916** [comment]
Google浏览器


| |
张国伟
|
|
zhangguowei0916@126.com
|
签名由网易邮箱大师定制
在2019年8月12日 14:10，KevinMint<notifications@github.com> 写道：


我测试了1000条数据并未重现该问题，请问是否还有其他条件会产生这种情况。

**Comment by zhangguowei0916** [comment]
chrome


| |
张国伟
|
|
zhangguowei0916@126.com
|
签名由网易邮箱大师定制
在2019年8月12日 15:04，张国伟<13666362798@126.com> 写道：
Google浏览器


| |
张国伟
|
|
zhangguowei0916@126.com
|
签名由网易邮箱大师定制
在2019年8月12日 14:10，KevinMint<notifications@github.com> 写道：


我测试了1000条数据并未重现该问题，请问是否还有其他条件会产生这种情况。
