### ISSUE TITLE
支持excel公式吗？

### ISSUE THREAD

**Issue by lanbin45** [KevinMint55/vue-willtable#40]
RT
我有个功能，想要让单元格支持公式，不知道这个组件是否支持？期待回复

**Comment by KevinMint55** [comment]
> RT 我有个功能，想要让单元格支持公式，不知道这个组件是否支持？期待回复

不好意思，暂不支持

**Comment by lanbin45** [comment]
您好，您的邮件我已收到~~我会及时查看的  (*^__^*)
