### ISSUE TITLE
自带的demo显示效果与自带截图效果不一致

### ISSUE THREAD

**Issue by hhaoao** [KevinMint55/vue-willtable#6]
npm下载的vue-willtable
包与[demo](https://demo.kevinmint.com/willtable/)一样编辑框位置都是无法达到[项目readme截图所示](https://camo.githubusercontent.com/96505049ca1f2a462e6db5317bacd3059d064648/68747470733a2f2f71696e69752e6b6576696e6d696e742e636f6d2f77696c6c7461626c65312e676966)的效果。

npm版本:
```cmd
λ npm --version
6.13.4
```

测试vue-willtable(1.1.3)项目时的包列表：
```cmd
λ npm list --depth 0
hello-world@0.1.0 F:\shortcut\temporary-project\vuetemp\hello-world+-- @babel/plugin-transform-runtime@7.7.6
+-- @babel/preset-env@7.7.6
+-- @babel/runtime@7.7.7
+-- @vue/cli-plugin-babel@4.1.1
+-- @vue/cli-plugin-eslint@4.1.1
+-- @vue/cli-service@4.1.1
+-- axios@0.19.0
+-- babel-eslint@10.0.3
+-- babel-plugin-component@1.1.1
+-- core-js@3.6.0
+-- element-ui@2.13.0
+-- eslint@5.16.0
+-- eslint-plugin-vue@5.2.3
+-- node-sass@4.13.0
+-- sass-loader@8.0.0
+-- showdown@1.9.1
+-- vue@2.6.10
+-- vue-cli-plugin-element-ui@1.1.4
+-- vue-template-compiler@2.6.10
`-- vue-willtable@1.1.3
```
出现问题截图与项目截图对比：
项目readme截图：
![项目readme截图](https://user-images.githubusercontent.com/11269610/71617353-a85efa00-2bf5-11ea-9b04-3e5ce49c3909.png)

出问题截图：
![出问题截图](https://user-images.githubusercontent.com/11269610/71617358-ac8b1780-2bf5-11ea-9478-588312b80c43.png)

**Comment by KevinMint55** [comment]
> npm下载的vue-willtable
> 包与[demo](https://demo.kevinmint.com/willtable/)一样编辑框位置都是无法达到[项目readme截图所示](https://camo.githubusercontent.com/96505049ca1f2a462e6db5317bacd3059d064648/68747470733a2f2f71696e69752e6b6576696e6d696e742e636f6d2f77696c6c7461626c65312e676966)的效果。
> 
> npm版本:
> 
> ```batchfile
> λ npm --version
> 6.13.4
> ```
> 
> 测试vue-willtable(1.1.3)项目时的包列表：
> 
> ```batchfile
> λ npm list --depth 0
> hello-world@0.1.0 F:\shortcut\temporary-project\vuetemp\hello-world+-- @babel/plugin-transform-runtime@7.7.6
> +-- @babel/preset-env@7.7.6
> +-- @babel/runtime@7.7.7
> +-- @vue/cli-plugin-babel@4.1.1
> +-- @vue/cli-plugin-eslint@4.1.1
> +-- @vue/cli-service@4.1.1
> +-- axios@0.19.0
> +-- babel-eslint@10.0.3
> +-- babel-plugin-component@1.1.1
> +-- core-js@3.6.0
> +-- element-ui@2.13.0
> +-- eslint@5.16.0
> +-- eslint-plugin-vue@5.2.3
> +-- node-sass@4.13.0
> +-- sass-loader@8.0.0
> +-- showdown@1.9.1
> +-- vue@2.6.10
> +-- vue-cli-plugin-element-ui@1.1.4
> +-- vue-template-compiler@2.6.10
> `-- vue-willtable@1.1.3
> ```
> 
> 出现问题截图与项目截图对比：
> 项目readme截图：
> ![项目readme截图](https://user-images.githubusercontent.com/11269610/71617353-a85efa00-2bf5-11ea-9b04-3e5ce49c3909.png)
> 
> 出问题截图：
> ![出问题截图](https://user-images.githubusercontent.com/11269610/71617358-ac8b1780-2bf5-11ea-9478-588312b80c43.png)

你好，我的demo是和最后发布版本保持一致。出现这个问题应该是由于浏览器兼容性。我目前测的火狐会出现这种情况，你可以尝试使用谷歌、Edge以及ie10以上等浏览器打开看看。我会在下个版本中修复此兼容性问题，感谢提出。
