### ISSUE TITLE
需要一份详细的文档

### ISSUE THREAD

**Issue by Redkucha** [KevinMint55/vue-willtable#9]
能提供一份比较详细的文档吗？包含比如 多种数据类型校验方法，如果table中用了slot，就不能向下复制了，这些问题该怎么解决

**Comment by KevinMint55** [comment]
> 能提供一份比较详细的文档吗？包含比如 多种数据类型校验方法，如果table中用了slot，就不能向下复制了，这些问题该怎么解决

- 目前数据校验是内置的对多种基本类型的判断，比如数字、日期、月份以及下拉选择，当某列选择了相应数据类型会自动进行校验。
- 文档目前主要是对使用组件所需要知道的属性与API进行描述，并不会对某些方法实现进行详细描述，你所指的比较详细文档具体指的哪些方面？
- 目前table组件并不支持slot插入，为何会有这种前置条件？
